import Head from 'next/head';
import { useState } from 'react';

import { AddButton } from '@/components/AddButton';
import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';
import { Loader } from '@/components/Loader';
import { TodoInput } from '@/components/todoInput';
import { useFirebase } from '@/hooks/useFirebase';

export default function Home() {
    const { todoList, addNewTodo } = useFirebase('todoList');

    const [inputTodo, setInputTodo] = useState<string>('');

    const loading = !todoList && true;

    const addTodo = (title: string) => {
        addNewTodo({
            title: title,
            isDone: false,
        });
    };

    return (
        <div>
            <Head>
                <title>Todo List</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className="h-screen flex items-center flex-col pt-28">
                {/* Input Area */}
                <div className="flex">
                    <TodoInput {...{ inputTodo, setInputTodo }} />
                    <AddButton {...{ inputTodo, setInputTodo }} />
                </div>

                {loading ? (
                    <Loader />
                ) : (
                    <ul>
                        {todoList &&
                            Object.entries(todoList).map(([, value], index) => {
                                // TODO: 各TODOに機能を持たせる
                                return <li key={index}>{value.title}</li>;
                            })}
                    </ul>
                )}
            </main>

            <Footer />
        </div>
    );
}
